# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_auto_20161107_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_url',
        ),
    ]
